version: "3.3"
services:
  elasticsearch:
    container_name: elasticsearch
    mem_limit: 2g
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    cap_add:
      - IPC_LOCK
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.0
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  elasticsearch-data: